version: "3.9"
services:
    nifi:
        image: apache/nifi:1.12.0
        environment:
            - NIFI_HOME=/opt/nifi/nifi-current
            - NIFI_LOG_DIR=/opt/nifi/nifi-current/logs
            - NIFI_TOOLKIT_HOME=/opt/nifi/nifi-toolkit-current
            - NIFI_PID_DIR=/opt/nifi/nifi-current/run
            - NIFI_BASE_DIR=/opt/nifi
            - NIFI_WEB_HTTP_PORT=9300
        volumes:
            - "nifioutput:/opt/nifioutput"
            - "nifiinput:/opt/nifi/input"
        ports:
            - "9300:9300"
        profiles:
            - nifi
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
        volumes:
            - elastic:/usr/share/elasticsearch/data
        profiles:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.0
        environment: 
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - "5601:5601"
        profiles:
            - elastic
    postgresql:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - postgres-vol:/var/lib/postgresql/data
        profiles:
            - backend
    pgadmin4:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_PASSWORD=pgadmin
            - PGADMIN_DEFAULT_EMAIL=pgadmin@gmail.com
        ports:
            - "8081:80"
        profiles:
            - backend
volumes:
    nifioutput:
    nifiinput:
    elastic:
    postgres-vol: